name: NanoMail
version: 0.2 #@version@ does not work!
main: com.github.nanodot.nanomail.NanoMail
api-version: 1.16
commands:
  nanomail:
    description: Command allows to use NanoMail system
    permission: nanomail.general
    aliases: [nm]
